apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: food-delivery
type: Opaque
stringData:
  datasource-url: jdbc:postgresql://postgres:5432/fooddb
  datasource-username: postgres
  datasource-password: postgres
