apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-frontend
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-frontend
  template:
    metadata:
      labels:
        app: food-frontend
    spec:
      containers:
        - name: frontend
          image: sandra040/food-frontend:latest
          ports:
            - containerPort: 80

